### ISSUE TITLE
IE浏览器

### ISSUE THREAD

**Issue by chuiliu** [chuiliu/dev-notes#11]
- 一些常用框架和库的对IE浏览器支持情况：
```
jQuery 1.x: >=IE6, jQuery 2.x: >=IE9
BootStrap: >=IE8
Vue: >=IE9
React v0.14: >=IE8, React v15+: >=IE9
```

- 常用的CSS属性对IE的支持情况
```css
:before/:after: >=IE8
background-size: >=IE9
div:hover >=IE7
min-width/min-height: >=IE8
max-width/max-height: >=IE7
inline-block: >=IE8
box-sizing: >=IE8
transform: >=IE9 (IE9: -ms-)
opacity: >=IE9
box-shaodow: >=IE9
:first-child: IE7+
```

- CSS Hack
```css
.wrap {
    _color: #000; /* IE6 */
    *color: #111; /* IE6-7 */
    color: #fff\9; /* IE6-8 */
}

```

- IE条件注释
注意：条件注释在IE10以及之后的版本均不支持
```html
<!--[if IE 8]>
    <link rel="stylesheet" type="text/css" href="ie8.css">
<![endif]-->
<!--[if lt IE 9]>
    <script src="html5shiv.min.js"></script>
    <script src="respond.min.js"></script>
<![endif]-->
```

- 让 IE6-9 识别并支持HTML5标签
[html5shiv](https://github.com/aFarkas/html5shiv)

- 让 IE6-8 支持 CSS3 媒体查询，min/max-width 
[response.js](https://github.com/scottjehl/Respond)
注意：
    1. 必须通过外部引入CSS，通过style书写在页面的方式无效
    2. response.js 必须在CSS之后引入
