### ISSUE TITLE
temp

### ISSUE THREAD

**Issue by chuiliu** [chuiliu/dev-notes#15]
```css
html,body,p,ul,ol,li,dl,dt,dd,iframe,hr,form,table,h1,h2,h3,h4,h5,h6 {
    margin: 0;
    padding: 0;
}
html,body {height: 100%;}
body {
    line-height: 1;
}
h1,h2,h3,h4,h5,h6 {
    font-weight: normal;
    font-size: 100%;
}
*,*:before,*:after {
    box-sizing: border-box;
}
ul,ol {
    list-style: none;
}
table {
    border-collapse: collapse;
    border-spacing: 0;
}
img {
    border: 0;
}
a[href],
input[type='submit'],
input[type='image'],
label[for],
select,
button {
    cursor: pointer;
}
input, button, select, textarea {
    outline: none;
    -webkit-appearance: none;
}
textarea {
    resize: vertical;
}
```
